# consts for indexes in WeatherReading tuple
DATE_INDEX = 0
MAX_TEMP_INDEX = 1
MEAN_TEMP_INDEX = 2
MIN_TEMP_INDEX = 3
MAX_HUMIDITY_INDEX = 4
MEAN_HUMIDITY_INDEX = 5
MIN_HUMIDITY_INDEX = 6

# ansi color codes
RED_COLOR = '\033[91m'
BLUE_COLOR = '\033[94m'
RESET_COLOR = '\033[0m'
